### ISSUE TITLE
Add additional shortLocations in createValidAzResourceName bicep module

### ISSUE THREAD

**Issue by kalalvishal** [SvenAelterman/BicepTemplate#12]
Add additional shortLocations in createValidAzResourceName bicep module

**Comment by SvenAelterman** [comment]
Will use the list from https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/modules/connectivity/locals.geo_codes.tf.json.

I don't know of a strategy to keep it updated though ☹️.
